// Dumps public.roadmap_items to seed.sql-shaped INSERT tuples on stdout.
//
// The board is mutable state edited through /admin/roadmap (see
// src/app/admin/roadmap/actions.ts) — anything created or re-statused there
// lives only in the database, not in seed.sql and not in git. This script is
// the missing export path: run it before and after any roadmap migration and
// diff the output, and reconcile drift back into supabase/seed.sql.
//
//   npm run dump:roadmap > /tmp/board-before.sql
//
// Reads with the service-role key, so it sees is_public = false rows too —
// never commit its raw output anywhere public without checking those.

import { getServiceRoleClient } from './lib/scrape-common'

type RoadmapRow = {
  phase: number
  category: string
  title: string
  description: string | null
  status: string
  dev_percent_complete: number
  is_public: boolean
  display_order: number
}

/** Postgres string literal: single quotes are escaped by doubling them. */
function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

function sqlValue(value: string | null): string {
  return value === null ? 'null' : sqlString(value)
}

function formatRow(row: RoadmapRow): string {
  return [
    `  (${row.phase}, ${sqlString(row.category)}, ${sqlString(row.title)},`,
    `   ${sqlValue(row.description)},`,
    `   ${sqlString(row.status)}, ${row.dev_percent_complete}, ${row.is_public}, ${row.display_order})`,
  ].join('\n')
}

async function main() {
  const supabase = getServiceRoleClient()

  const { data, error } = await supabase
    .from('roadmap_items')
    .select('phase, category, title, description, status, dev_percent_complete, is_public, display_order')
    .order('phase', { ascending: true })
    .order('display_order', { ascending: true })
    .order('id', { ascending: true })

  // Rule 7 — never swallow errors. A dump that silently returns nothing would
  // read as "the board is empty", which is the worst possible lie for a backup.
  if (error) {
    throw new Error(`roadmap_items select failed: ${error.message}`)
  }
  if (!data || data.length === 0) {
    throw new Error('roadmap_items returned no rows — refusing to emit an empty dump')
  }

  const rows = data as RoadmapRow[]
  let currentPhase: number | null = null

  // Phase headers are prefixed onto the first tuple of each phase rather than
  // pushed as separate entries, so joining with "," can never put a comma
  // after a comment line.
  const tuples = rows.map(row => {
    const header = row.phase === currentPhase
      ? ''
      : `${currentPhase === null ? '' : '\n'}  -- Phase ${row.phase}\n`
    currentPhase = row.phase
    return header + formatRow(row)
  })

  console.log(`-- Dumped from the live database at ${new Date().toISOString()}`)
  console.log(`-- ${rows.length} row(s). Generated by scripts/dump-roadmap.ts — do not hand-edit.`)
  console.log()
  console.log('insert into public.roadmap_items')
  console.log('  (phase, category, title, description, status, dev_percent_complete, is_public, display_order)')
  console.log('values')
  console.log(tuples.join(',\n') + ';')

  console.error(`\nDumped ${rows.length} row(s).`)
}

main().catch(err => {
  console.error(err instanceof Error ? err.message : err)
  process.exit(1)
})
