-- Step 7 exists. The umbrella the six calculators become.
--
-- Keep in sync with supabase/seed.sql (CI enforces this).

update public.roadmap_items
  set status = 'in_development',
      dev_percent_complete = 40,
      description = 'Initial version shipped 2026-09-01 as /calculators/system, step 7. The item asked for one flow with assumptions carried visibly, uncertainty shown where it enters, and a stated confidence band -- and named the failure it exists to prevent: "four tools that each look authoritative and quietly disagree is the worst configuration available." That is not hypothetical. Panel sizing rounds UP to a whole count from an energy target; array wiring must factor that count into whole strings inside a voltage window and a current limit. For the SG550WM against an SPH10048P at a -25.9 degC design low, EVERY ODD COUNT fails -- 9, 11, 13 and 15 have no safe arrangement while 10, 12, 14 and 16 do. The panel page says buy 11, the array page says nothing fits, and neither is wrong on its own terms. src/lib/system-design.ts does three things no single step structurally can: DISAGREEMENTS (the panel-count mismatch, a battery and inverter at different voltages, an array past the PV input, string fusing needed or unknown, panels sized but never wired), each with what each side says, why neither is wrong alone, what to do, and links back to both steps; ASSUMPTIONS WITH PROVENANCE -- every figure that shapes the result, which step set it, whether it is still the shipped default, what it changes downstream and how much it moves the answer, ranked by leverage rather than by step because a list in step order teaches nothing about which one to go and check; and a CONFIDENCE BAND that is deliberately a word rather than a percentage. A numeric interval would need error distributions for peak sun at this site, this roof''s soiling and this household''s behaviour, none of which exist, so printing "+/-20%" would be exactly the false precision the rest of the site refuses -- the reasons attached to the word are the useful part. A value equal to the shipped default is reported as "still at the default", never as "you did not choose this", because someone may have looked at 80% array derate and decided it was right. BatterySummary gained bankKwh, bankAh, autonomyDays, systemVoltage, the scenario label and the band -- it previously published only what the panel step needed (chemistry and round trip), so nothing downstream could say how big the battery was. Two bugs found in visual review and fixed: lighting up step 7''s href made every "is this step outstanding" check count the destination as unfinished work, which made chainComplete permanently false and left the confidence band permanently reporting a missing step; and the assumptions table rendered temperatures in Celsius while the rest of the chain defaults to Fahrenheit, including the cell rise, which is a DELTA and converts without the offset. Covered by src/lib/__tests__/system-design.test.ts. NOT DONE and deliberately out of this first pass: a printable bill of materials, any cost estimate, and cross-checking the protection step (which publishes no summary, so it cannot be detected as complete).'
  where title = 'System designer: one integrated sizing chain';
