-- The affiliate plumbing shipped in the same change as this migration and earns
-- nothing, because JOINING a programme has prerequisites that nothing on this
-- board captured. Recording them as their own item rather than burying them in
-- the disclosure item's description, because they are not disclosure work and
-- they are not code.
--
-- is_public = false, like the price-coverage item it sits beside: this is
-- commercial readiness and application timing, not a user-facing feature.
--
-- Keep in sync with supabase/seed.sql (CI enforces this).

insert into public.roadmap_items
  (phase, category, title, description, status, dev_percent_complete, is_public, display_order)
values
  (1, 'infrastructure', 'Affiliate prerequisites: production, then analytics, then apply',
   'The affiliate link mechanism shipped 2026-09-15 and earns nothing, because joining a programme has prerequisites nothing on this board captured. Both were VERIFIED on 2026-09-15 rather than assumed. NO PUBLIC SITE EXISTS: zonzelf.com and zonzelf.app both resolve to Microsoft 365 MX records and nothing else — no A record, www.zonzelf.com is NXDOMAIN, and neither answers over HTTPS — while staging.zonzelf.app stays VPN-only with no public DNS. An affiliate reviewer has nothing to open. NO ANALYTICS EXIST EITHER: no analytics package in package.json, no gtag/GTM/Plausible/PostHog/Vercel Analytics anywhere in src/, and no script tag in the root layout. The only client-side state is the Supabase auth cookie and the calculators'' own localStorage, neither of which is a number anyone can share. WHY THE SECOND ONE MATTERS MORE THAN IT LOOKS: Signature Solar''s application asks "Are you willing to share your analytics with us?" as a REQUIRED question, alongside Reddit/TikTok/YouTube handles, whether you operate in the solar INSTALLATION industry, and willingness to travel to their promotional events. That is an application built for influencers and creators — the DIY-solar YouTube audience — and their own programme page describes it as for "individuals with solar experience". "Analytics" there means audience metrics that prove reach. ZonZelf is a different shape: a calculator and guide site, which can still qualify, but not with no traffic, no numbers and no publicly visible product. A decline sets a prior that is harder to walk back than a first application made at the right moment, so the sequencing is the point of this item. THE ORDER: (1) production deploy so the site is publicly reachable — Cloudflare was already chosen, see the production hosting work; (2) privacy-respecting analytics, so there is a number to share; (3) a few months of real traffic; (4) apply. AWIN IS THE GENTLER FIRST APPLICATION once (1) is done — a standard publisher form reviewed within two working days, a $5 deposit refunded against the first commission payment, and no stated traffic minimum, though advertisers do decline low-traffic publishers in practice. It is also the route to SunGoldPower, which covers seven of the published battery rows; ShareASale, named in the older affiliate-readiness item as an alternative, closed on 6 October 2025 and is now part of Awin. ON THE ANALYTICS CHOICE: Cloudflare Web Analytics is free, cookieless and needs no consent banner, and hosting is going to Cloudflare anyway. That matters beyond convenience — /privacy currently states "We do not currently use advertising or third-party tracking cookies", which is true today and which a cookie-based tool would falsify, and GDPR applies to EU visitors regardless of the US LLC. Whatever is chosen, /privacy is updated in the same change.',
   'planned', 0, false, 97);
