-- The legal pages get a reachable contact channel.
--
-- The item was blocked on one decision (email vs. contact form). Email won
-- because a form is a backend, a spam surface, and a store of personal data
-- that the privacy policy would then have to describe -- new processing, to
-- solve a problem an mailto does not have.
--
-- Keep in sync with supabase/seed.sql (CI enforces this).

update public.roadmap_items
  set status = 'in_test',
      dev_percent_complete = 90,
      description = 'Shipped 2026-09-08. Three Microsoft 365 shared mailboxes -- privacy@zonzelf.com on /privacy, legal@zonzelf.com on /terms, hello@zonzelf.com on /accessibility -- replacing the four [TODO] placeholders. Email rather than a contact form: a form is a backend, a spam surface, and a store of personal data the privacy policy would then have to describe, which is new processing to solve a problem a mailto does not have. Shared mailboxes rather than licensed users: no licence cost, 50 GB each, and sign-in stays blocked so there is no password or MFA to manage. SEPARATE MAILBOXES RATHER THAN ALIASES ON ONE, because Exchange Online send-from-alias behaviour is inconsistent across Outlook clients and a reply leaving as the wrong address contradicts the address the page published. SEND AS RATHER THAN SEND ON BEHALF, because the latter renders as "Vincent Raaijmakers on behalf of privacy@zonzelf.com" and puts the natural person on every GDPR reply while the LLC does not yet exist. privacy@ is linked TWICE on /privacy, in "Your rights" where a right is actually exercised as well as in "Contact", because an address two headings below the sentence inviting its use fails the person who needs it most. The privacy processor list now names Microsoft 365 (Exchange Online) alongside Supabase, since mail is where legal correspondence and any personal data inside it lands. DNS, all verified resolving with dig: MX and SPF on both domains; DKIM enabled through the Security portal, which Microsoft does NOT do for custom domains and is the step most setups miss -- without it SPF is the only authentication and it breaks on any forwarding; DMARC with rua= on both; plus the zonzelf.com._report._dmarc.zonzelf.app authorization record, without which cross-domain aggregate reports are silently dropped. THE MICROSOFT-ONLY ROOT SPF ON zonzelf.app DOES NOT BREAK RESEND auth mail: Resend returns through send.zonzelf.app, which carries its own MX and include:amazonses.com, and DKIM d=zonzelf.app aligns, so DMARC passes on the DKIM half -- do not "fix" the root SPF by adding include:amazonses.com, it is unnecessary and burns one of ten lookups. NOT done here, deliberately: the "Governing law" [TODO] on /terms, which belongs to the entity/jurisdiction item and is blocked on the LLC being filed. The professional-review and clickwrap gates stay independent -- a reachable address is not assent and is not legal review. The mailboxes live in the seecago.com tenant rather than a ZonZelf one, because a separate tenant needs a paid licence to have anything to send from; moving them at LLC formation is cheap now and expensive after years of archived mail.'
  where title = 'Legal: real contact channel';
