-- US-first audience, and every temperature on the site was Celsius.
--
-- Keep in sync with supabase/seed.sql (CI enforces this).

insert into public.roadmap_items
  (phase, category, title, description, status, dev_percent_complete, is_public, display_order)
values
  (1, 'calculators', 'Temperatures in Fahrenheit, with the two exceptions that stay Celsius',
   'Shipped 2026-08-30 from user feedback. CLAUDE.md says US LLC, US-first audience, NEC 310.16 -- and every temperature on the site was Celsius, which is the wrong default for the people it is written for. src/lib/temperature.ts adds a display unit, defaulting to Fahrenheit, with the toggle on the array step. Everything is STORED in Celsius always and converted only at the boundary, because the physics runs in Celsius and storing the display unit would mean every calculation had to know which unit its inputs were in. Three traps a find-and-replace would have hit, all silent: (1) A DIFFERENCE IS NOT A POINT ON THE SCALE. "Cell rise in sun: 30 degC" means the panel runs 30 degrees hotter than the air. Converting it with the +32 offset gives 86 degF, which is plausible-looking and wrong -- the answer is 54. Absolute and delta conversions are separate named functions and a test asserts both, including the wrong answer, so the distinction stays visible. (2) SOME TEMPERATURES ARE NAMES, NOT MEASUREMENTS. The 60/75/90 degC terminal ratings are the names of NEC Table 310.16 columns and are stamped on lugs and cable jackets in Celsius in the US too. Rendering them as 140/167/194 degF would make the calculator disagree with the label in the user hand, so they stay as printed, with a note saying that is deliberate. (3) COEFFICIENTS ARE PUBLISHED PER DEGREE CELSIUS. IEC 61215 requires it, so a coefficient in %/degF appears on no datasheet. Converting it would leave the user unable to match our figure against their panel. The coefficient fields stay %/degC and the Voc and Vmp formulas are shown in Celsius with the Fahrenheit value alongside for orientation, with a note explaining why the formula did not follow the rest of the page. Covered by src/lib/__tests__/temperature.test.ts.',
   'in_test', 90, true, 93);
