-- The array wiring step ships, and with it the teaching that has to sit behind
-- it. CLAUDE.md's legal posture is that guides teach and calculators show the
-- derivation; a string calculator that emits a number with no explanation
-- behind it is the Jeppesen chart rather than the book, so the guide is part of
-- the item rather than a follow-up to it.
--
-- Keep in sync with supabase/seed.sql (CI enforces this).

update public.roadmap_items
  set status = 'in_test',
      dev_percent_complete = 90,
      description = 'Shipped as step 5, "Array wiring", at /calculators/strings, with src/lib/pv-string.ts as the model and /guides/strings-and-mppt as the teaching behind it. Covers both halves rather than only the series one: series count against the maximum PV input voltage, parallel count against the tracker''s input current, and NEC 690.9(A) string fusing — (n-1) x Isc x 1.25 against the module''s max series fuse rating, which is where the folk rule "one or two strings need no fuses, three or more do" actually comes from. THREE ceilings are modelled, not one, because datasheets publish them separately and conflating them is the whole failure: the bottom of the MPPT window (below it nothing is harvested), the top of the window (clipping, survives), and the absolute max PV input (destroyed). The first two are CAPACITY and the third is PROTECTION, and the page renders them differently on that basis. TWO temperatures, not one: the design low sets the cold Voc against the damage ceiling, and a hot CELL temperature — ambient plus a 30 degC rise — sets the sagging Vmp against the tracking floor. The second is the mechanism behind the widespread "design to 220V, not the 100V minimum" advice; the calculator models it as a headroom target over the floor rather than repeating a number that belongs to someone else''s panel and someone else''s climate. Vmp coefficients are rarely published, so it falls back to Pmax and then to Voc, naming which it used, because the Voc fallback UNDERSTATES the sag and is the optimistic direction. peak-sun.ts gained designLowC, recordLowC and designHighC per region, with the page saying plainly that this is the input it most needs replacing — regional records come from frost hollows and mountains rather than from where people build, and California''s -43 degC would halve a coastal string for weather it will never see. A bug found in visual review and locked by a test: when NO arrangement is safe the list was sorted by series count, which put the 12-in-series option — 668V into a 500V input — at the top as "best". Failures are now ordered by what they violate, and the card says "None" in ink rather than an arrangement in gold. Covered by src/lib/__tests__/pv-string.test.ts, including the guide''s worked numbers, so the guide and the calculator cannot drift apart. Still blocked on the licensed-electrician sign-off.'
  where title = 'Calculators: string voltage vs MPPT input window';

update public.roadmap_items
  set description = 'Plain-English explainers woven into guides and calculators, not a separate wizard. Differentiator #1. Started 2026-08-25 after an audit of where each concept actually appears found the calculators had outrun the teaching badly: duty cycle, load profiles, the three-stage efficiency chain, the battery scenario band, dark hours and the cooling/heating asymmetry were all enforced by tools and explained on no page at all, and the glossary — whose entire job this is — defined none of the new vocabulary. A beginner met "Duty %", "Runs: Cooling" and "156% of Isc" with nowhere to look them up, which is differentiator #1 inverted. Done: the glossary gained ampacity, autonomy, continuous load, design current, duty cycle, Isc, OCPD and round-trip efficiency, cross-linked to the calculators and guides that use them; the wiring guide gained the 125% continuous rule and the 156% PV rule. 2026-08-30, alongside the array wiring step: /guides/strings-and-mppt was written as the lecture behind it — the four label figures and why a panel has no single voltage, series versus parallel, the three-number MPPT window, both temperature formulas with worked examples in each direction, why "just use 220V" is a rule of thumb and what it stands in for, the string-fusing inequality, and an end-to-end worked design. Its numbers are locked to src/lib/pv-string.ts by test, so the guide cannot drift from the tool it teaches. The glossary gained Voc, Vmp, Imp, temperature coefficient, STC, string, MPPT window, string fuse and max series fuse rating. Remaining: the efficiency chain belongs in /guides/how-it-works, and the autonomy-vs-overnight distinction plus the cooling/heating asymmetry belong with battery sizing. No test can tell you an explanation is clear, so this one is verified by a person reading it.'
  where title = 'Guided beginner onboarding';
