-- The calculator pickers shipped: /calculators/inverter and /calculators/strings
-- offer published catalogue models. in_test: on develop only, Safari unchecked.
--
-- Keep in sync with supabase/seed.sql (CI enforces this).

update public.roadmap_items
  set status = 'in_test',
      dev_percent_complete = 85,
      description = 'Session 3 of the component-catalogue work, planned 2026-09-30, and the user-facing half of it: an easier way to choose a panel and an inverter from what ZonZelf already has, instead of typing a datasheet in. Depends on "Admin: component catalogue" -- only published, datasheet-verified models are offered. The inverter step and the strings step read published component_models and their specs instead of the INVERTER_PRESETS and PANEL_PRESETS arrays. A searchable picker, narrowed to what fits the design so far: inverters by battery voltage and continuous watts, panels that wire into whole strings inside the chosen tracker''s window at the site''s design low. Physical fields feed the form-factor work in "Panel choice: form factor, granularity and the physical fields". Each pick shows its retailer listings with a dated price and the affiliate disclosure (src/lib/affiliate.ts), per-panel price for pallets, and the minimum order. Typing a datasheet in by hand stays a first-class path. Differentiator #1 -- a beginner picks a real product and sees why it fits -- and the affiliate line for the two largest purchases after the battery. SHIPPED 2026-09-30 (src/lib/catalog-picker.ts, src/lib/use-catalog.ts, src/components/calculators/CatalogPicker.tsx). The inverter and strings steps now offer every PUBLISHED catalogue model -- which the database only allows once its specs are verified from the datasheet -- instead of the hand-written arrays. Each card shows the cheapest CURRENT offer per unit (a pallet divided by its size, an expired price excluded), the shop, the date, a Buy link with the FTC disclosure driven by the same anyPaid() boolean as the battery shelf, the untagged datasheet link, and the Umami shop-click event. INVERTERS rank smallest-that-covers-the-house first, with a capacity badge: covers with headroom, covers without the 25% headroom, too small. PANELS rank by $/W, with size and weight. THE LEGAL LINE: the panel shelf never says a panel "fits your inverter" -- how many may go in a string is a PROTECTION output and appears only with its derivation, which the strings step shows after the pick. Inverter demand coverage is CAPACITY and is labelled. PRESETS KEPT: commissioning.ts keys its SPH menu map on preset ids, so a catalogue pick carries its preset id when it IS a preset (matched on brand plus the preset model as a whole word), and the pickers fall back to the presets if the catalogue cannot load. FIRST LIVE STATE: three inverters (EG4 6000XP with a Signature Solar price; SPH8048P and SPH10048P with none) and two panels (Aptos 440W at $184.80 per panel in a pallet of 31, verified by the operator; SG550WM with none). Rendered and checked in headless Chrome against the live catalogue; Safari not yet checked.'
  where title = 'Calculators: pick real components from the catalogue';
