-- Second of the two jobs this item named: widening the vendor mix. See
-- scrape-a1solarstore.ts.
--
-- Keep in sync with supabase/seed.sql (CI enforces this).

update public.roadmap_items
  set dev_percent_complete = 25,
      description = 'Affiliate is the primary revenue line, and the catalogue cannot currently carry it. All three EG4 models now have a price and a retailer, captured from Signature Solar (scripts/scrape-signaturesolar.ts, a hand-verified SKU-to-URL mapping — the storefront splits "Indoor" and "AllWeather" variants of the same capacity into separate products, so a naive title match would have picked the wrong one half the time). battery_models gained retailer and retailer_url columns rather than overwriting source_url, which stays the manufacturer spec citation. Vendor-mix widening has started: Bluetti turned out not to fit at all and was dropped from the plan, because its battery packs are ecosystem-locked to its own power stations rather than usable with any inverter (its own FAQ: the B300K "can only be charged by connecting to the AC500/AC300/AC200L/AC200MAX") — the same lock-in this project already refuses on the monitoring side. A1 SolarStore, a multi-brand reseller with its own affiliate program, added Discover Energy as a new brand instead (scripts/scrape-a1solarstore.ts): a 5.12kWh 48V rack-mount model at $1,683.40, hand-verified against the product page''s own spec text rather than inferred. All new and updated rows are unpublished pending admin review. Remaining: Victron (10 models, no direct affiliate programme, editorial only); more of A1 SolarStore''s catalogue is worth a look (spotted but not yet verified: a Midnite Power 314Ah battery, and an EG4 "Indoor" 314Ah variant this catalogue is missing entirely) but its listings mix in bulk lead-acid pallets and bundled inverter+battery kits that do not belong here, so each addition needs the same hand verification as Discover Energy. The FTC affiliate-disclosure item must still land before any of these links go live.'
  where title = 'Battery catalogue: price coverage and vendor mix for affiliate';
