-- The coldest-expected temperature stops being the weakest input on the page.
--
-- It decides how many panels may go in series, which makes it a
-- protection-register input, and the first version of it was ten hand-written
-- regions -- one of which was "Texas / Arizona". The page had to admit they
-- were barely usable. Derived per-place figures show why: Phoenix's design low
-- is about -1 degC and Flagstaff's about -16 degC, both in Arizona. A single
-- regional number is badly wrong for at least one of them, and being wrong on
-- the WARM side is what destroys inverters.
--
-- A live weather-API lookup would be more accurate still and was rejected
-- deliberately: /calculators promises "All calculators run in your browser --
-- no data is sent anywhere", and that promise is worth more than the precision.
-- The lookup happens once at development time and ships as static data.
--
-- Keep in sync with supabase/seed.sql (CI enforces this).

update public.roadmap_items
  set description = 'Fixed 2026-08-30, after the array-wiring step shipped with the weakest possible version of its most important input. The coldest expected temperature sets a string''s Voc and therefore how many panels may go in series, so it is a protection-register input -- and it was ten hand-written regions, one of which was "Texas / Arizona". src/lib/site-climate.ts now carries named PLACES rather than regions, each derived from thirty years (1995-2024) of ERA5 daily minimums and maximums via scripts/derive-site-climate.ts, which is committed so the data is reproducible and auditable. Two cold figures per place, both defensible and both offered: designLowC is the mean of the thirty annual minimums -- ASHRAE''s extreme annual mean minimum, computed by its own definition rather than approximated, and the figure NEC 690.7 actually points at -- and recordLowC is the coldest single day in the window, one click away for a cautious builder, the same pattern as the panel step''s "size against December". The justification is in the data: Phoenix''s design low is about -1 degC and Flagstaff''s about -16 degC, both Arizona; Sacramento about -2 degC and Truckee about -14 degC, both California. The old single row per region would have sized one of each pair roughly ten degrees too WARM, which is the direction that destroys inverters, and a test now asserts the Phoenix/Flagstaff spread so nobody collapses it back. A live weather-API lookup would be better still and was rejected on purpose: /calculators promises that nothing is sent anywhere, and that promise is worth more than the extra precision, so the fetch happens once at development time and ships static -- the app makes no network call. What it is still not: anybody''s actual site. ERA5 smooths local extremes over a ~25km grid, cold air pools in valleys, and a nearby station''s all-time record is usually colder (Denver''s real record is near -45 degC against -36.5 degC in this window). The page says so, keeps the field editable, and carries a panel naming the three ways to get a real local figure -- station record, ASHRAE handbook, or ask a local installer -- with the rule that when unsure you go colder, because that costs harvest and buys the inverter. Temperature columns were removed from peak-sun.ts in the same change: sun hours stay regional because irradiance genuinely varies more smoothly than a cold snap does, and two sources for one number is how they drift. SiteConditions.recordLowC was also renamed lowestExpectedC, because it holds whichever figure the user chose and a field named for the record while usually holding the design value is the same-word-different-meaning drift that has bitten this codebase three times.'
  where title = 'Calculators: string voltage vs MPPT input window';

update public.roadmap_items
  set dev_percent_complete = 55,
      description = 'Started 2026-08-30. src/lib/inverter-sizing.ts and src/lib/pv-string.ts carry INVERTER_PRESETS and PANEL_PRESETS behind an admission gate: every figure from the manufacturer''s own datasheet, opened and read, with a reachable sourceUrl and the matching review module passing. Four rows so far. Inverters: Sun Gold Power SPH8048P and SPH10048P (manufacturer manual V1.3 pp.58-59) and the EG4 6000XP (spec sheet VER 1.4.4). The EG4 row is the argument for the gate — refused on first attempt because its window and per-tracker current came from a search index, and when the PDF itself became readable the search figure proved WRONG: 25 A is the MAX. SHORT CIRCUIT INPUT CURRENT while MAX. USABLE INPUT CURRENT is 17 A. Recording 25 A as usable would have permitted about half again as many parallel strings as the tracker can convert, silently. That correction closed a modelling gap: pv-string.ts now treats current as a pair exactly like voltage, damage limit versus harvest limit. Panels: the Sun Gold Power SG550WM, from the manufacturer''s own datasheet served off their Shopify CDN (their own store, so it is their document, not a reseller''s transcription). A useful first row because it publishes all three fields the string maths needs and many sheets omit: the Voc coefficient, the Pmax coefficient, and the 25 A maximum series fuse rating. Its -0.35%/degC Voc coefficient is at the steep end, so it gains more voltage in cold than most: at a -25.9 degC design low it reaches 58.5 V against a 49.7 V label, taking eight in series on a 500 V input where the STC figure suggests ten. src/lib/panel-review.ts is the physics-shaped check, sibling of inverter-review.ts: Vmp below Voc, Imp below Isc, Pmax equal to Vmp x Imp within 5%, fill factor between 0.6 and 0.9, a NEGATIVE Voc coefficient, and a series fuse rating above Isc. SCRAPER FINDING, 2026-08-30: sungoldpower.com product pages DO carry an HTML spec table, but it omits the temperature coefficients and the maximum series fuse rating entirely — exactly the two protection-critical fields. An HTML-only scraper would emit rows that look complete and cannot size a string, silently falling back to a coefficient that understates cold Voc. A panel scraper therefore needs PDF text extraction, which is a devDependency decision not yet taken. Their product pages also cover more than one model in a single table (the 550 W page carries the SG450WM alongside it), so column selection needs the same hand verification the battery scrapers documented. Remaining: that scraper, Supabase panel_models and inverter_models tables with RLS, and /admin review queues mirroring /admin/batteries. Typing a datasheet in by hand stays a first-class path.'
  where title = 'Component spec library: inverters and panels';
