-- The published-row review gate half of the scraper autonomy item shipped.
-- The scheduling half has not, and it was always the half that had to wait:
-- turning on a weekly re-scrape while the upsert still overwrote live rows
-- would have automated the bug rather than the work.
--
-- Keep in sync with supabase/seed.sql (CI enforces this).

update public.roadmap_items
  set status = 'in_development',
      dev_percent_complete = 60,
      description = 'Two halves. THE REVIEW GATE SHIPPED 2026-09-09; the re-scrape schedule has not, and had to wait -- turning on a weekly job while the upsert still overwrote live rows would have automated the bug. The bug was real, not theoretical: scripts/lib/scrape-common.ts upserted `on conflict (source_url)`, which rewrote an already-published row''s specs and price on the SECOND run of any scraper with is_published left true, so a row listed on /calculators/battery could change with nobody in the loop. A SECOND VICTIM of the same overwrite had gone unnoticed: scrape-eg4.ts emits price_usd: null because EG4''s own site lists no price, and scrape-signaturesolar.ts fills that price in from the reseller -- so every EG4 re-scrape wiped the affiliate price, the field the primary revenue line depends on, off all three EG4 rows. The fix routes every scraper write through one gate: an UNPUBLISHED row is still written in place (nothing is live to protect, and it already sits in the review queue), while a PUBLISHED row''s change lands in the new battery_model_revisions table as a proposal and the live row is not touched. proposed/previous are jsonb because a proposal is a PATCH, not a row -- scrape-signaturesolar.ts proposes only price_usd/retailer/retailer_url, and nullable mirror columns could not tell "proposes null" apart from "has no opinion". TWO KINDS OF SILENCE are now distinguished, which is what fixed the second bug: an absent key means the scraper has no opinion, and a key present but null means the source page did not state the value -- neither ever clears a value that is already there. A partial unique index allows one open proposal per battery, so a weekly job replaces its own earlier proposal instead of stacking one per battery per week into a queue nobody reads; and a proposal identical to one a reviewer already rejected is not re-raised, while any different value proposes again. scrape-signaturesolar.ts stopped setting is_published = false on the row it updates -- that was safe but took a live battery off the calculator to do it, on a scraper whose whole job is a routine price refresh. /admin/batteries gained a "Proposed changes to live rows" section that diffs live against scraped per field and runs the same battery-review.ts checks against the row AS IT WOULD BE, so a proposal that would push a live battery to $32/kWh flags before it is applied rather than after; applying it IS the re-approval. is_published is deliberately not a field a proposal can carry (SCRAPED_FIELDS in src/lib/battery-revision.ts, which the apply action filters the stored jsonb through), so no proposal can publish a row. REMAINING: the scheduled re-scrape itself (GitHub Actions, weekly/monthly -- battery specs do not change daily) for the five live scrapers. That is now safe to turn on, which it was not before.'
  where title = 'Battery scraper: re-scrape scheduling + published-row review gate';

-- The pipeline item carried the bug in its own description as a known
-- limitation. It is no longer true, and a roadmap that still says so is worse
-- than one that never mentioned it.
update public.roadmap_items
  set description = 'battery_models table + scripts/scrape-*.ts. Collects real battery model specs (brand, capacity, voltage, DoD) from manufacturer sites so the battery calculator can eventually recommend "4x EG4 LL-S 100Ah" instead of just a kWh number. Rows land unpublished; an admin review step (part of the admin scrapers item) gates anything reaching a visitor. Five scrapers live and wired into package.json: EG4, Victron, SunGoldPower, Signature Solar and A1 SolarStore (scrape:eg4, scrape:victron, scrape:sungoldpower, scrape:signaturesolar, scrape:a1solarstore) — Renogy was ruled out by robots.txt, which explicitly disallows AI crawlers. Scraping stays manual-only: there is still no scheduled re-run. The overwrite that used to make one dangerous is fixed as of 2026-09-09 — a re-scrape no longer rewrites an already-published row, it proposes the change in battery_model_revisions and an admin applies it in /admin/batteries (see "Battery scraper: re-scrape scheduling + published-row review gate", where the schedule itself is what remains). A weekly cloud routine to extend this same pipeline to inverters and panels is scheduled separately once repo access for it is connected.'
  where title = 'Battery spec data pipeline (scraper)';
