-- Correction, not new work: the Discover Energy row's source_url pointed at
-- A1 SolarStore's product page, which is exactly what battery_models'
-- source_url column comment says not to do — it's the manufacturer spec
-- citation, and a reseller page isn't that, however accurate it happened to
-- be. Caught by a question about whether the brand belonged at all, since
-- discoverenergysys.com has no storefront of its own.
--
-- Keep in sync with supabase/seed.sql (CI enforces this).

update public.roadmap_items
  set description = 'Affiliate is the primary revenue line, and the catalogue cannot currently carry it. All three EG4 models now have a price and a retailer, captured from Signature Solar (scripts/scrape-signaturesolar.ts, a hand-verified SKU-to-URL mapping — the storefront splits "Indoor" and "AllWeather" variants of the same capacity into separate products, so a naive title match would have picked the wrong one half the time). battery_models gained retailer and retailer_url columns rather than overwriting source_url, which stays the manufacturer spec citation. Vendor-mix widening has started: Bluetti turned out not to fit at all and was dropped from the plan, because its battery packs are ecosystem-locked to its own power stations rather than usable with any inverter (its own FAQ: the B300K "can only be charged by connecting to the AC500/AC300/AC200L/AC200MAX") — the same lock-in this project already refuses on the monitoring side. A1 SolarStore, a multi-brand reseller with its own affiliate program, added Discover Energy Systems as a new brand instead (scripts/scrape-a1solarstore.ts): a 5.12kWh 48V rack-mount model at $1,683.40. Discover Energy Systems sells through a dealer network with no storefront of its own, same as Victron — the row first cited A1 SolarStore''s product page for specs, which was caught as exactly the mistake source_url exists to prevent, so specs are now hardcoded from the manufacturer''s own datasheet (verified 51.2V, 100Ah, 5.12kWh, 100% usable DoD against A1 SolarStore''s numbers, which matched) and only price is scraped live from the retailer. All new and updated rows are unpublished pending admin review. Remaining: Victron stays editorial (no affiliate programme found); more of A1 SolarStore''s catalogue is worth a look (spotted but not yet verified: a Midnite Power 314Ah battery, and an EG4 "Indoor" 314Ah variant this catalogue is missing entirely) but its listings mix in bulk lead-acid pallets and bundled inverter+battery kits that do not belong here, so each addition needs the same manufacturer-datasheet verification as Discover Energy Systems. The FTC affiliate-disclosure item must still land before any of these links go live.'
  where title = 'Battery catalogue: price coverage and vendor mix for affiliate';
